<?php 
	// Provincies
	$provincies = array(

					"antwerpen" => array(

						'name' 	=> 	"Antwerpen",
						'title' 	=> 	"Dating Antwerpen",
						'info' 	=>	"Dating Antwerpen en omgeving heeft een groot aanbod van singles die willen daten in Antwerpen. Hier lopen nog teveel mooie en spannende vrouwen rond op zoek naar een knappe man. Tussen de contactadvertenties Antwerpen staan vrouwen in alle smaken. Deze vrouwen hebben nog geen keuze gemaakt. Maak jij de keuze voor deze dames en neem jij hun op date in Antwerpen? Stuur jouw nieuwe liefde dan snel een gratis berichtje en vraag haar mee voor een gezellige gratis date.",
						'tekst' 	=> 	"<h3>Wat te doen op een date in Antwerpen?</h3><p>Antwerpen telt het grootst aantal single vrouwen. Dit komt omdat er meer vrouwen als mannen leven en deze hebben allemaal nog niet hun partner voor het leven gevonden. Bij dating Antwerpen is het zelfs zo dat er meer dan 10.000 singles rond lopen op zoek naar hun droomman of vrouw. Wil je jouw single date meenemen naar de stad Antwerpen of liever in de omgeving ervan. De stad Antwerpen is the place to be voor een gezellige gratis date. Daten in Antwerpen en omgeving heeft genoeg opties om een date tot een succes te maken. Lees verder of zoek tussen de Dating Antwerpen een date.</p><h4>Waar kan jij het beste daten in Antwerpen</h4><p>In Antwerpen heb je namelijk de oude binnenstad die erg gezellig is. Daar zal jij met jouw date een tal van historische monumenten panden tegen komen. Er zijn genoeg winkeltjes en restaurants om een gezellige date in Antwerpen te hebben. Maar ook kunt u uw date meenemen naar een gezellige bar om wat te drinken. Wil jouw date liever winkelen? Ook dat kan, want de meeste bezoekers van Antwerpen, komen om te shoppen in de vele winkelstraten. <a href='https://www.allesoverantwerpen.nl/shopping/winkelstraten/meir.htm' target='_blank'>De Meir</a> is de bekenste winkelstraat waar uren geshopt kan worden. Vrouwen houden namelijk van winkelen en als je jouw date een belofte doet om samen te gaan shoppen, dan weet je zeker dat deze date geslaagd zal zijn. Er zijn zelfs bekende merken te vinden zoals Gucci en Louis Vuitton waar jouw date helemaal in de wolken mee kan laten lopen. Elke vrouw is gek op die merken en daarom zal daten in Antwerpen zeker een perfecte date zijn.</p><h4>Dating Antwerpen</h4><p>Voor nog een klein stukje historie is het natuurlijk ook leuk om jouw date mee te nemen naar <a href='https://www.visitantwerpen.be/nl/bezienswaardigheden/onzelievevrouwekathedraal' target='_blank'>Onze-Lieve-Vrouwe-kathedraal</a>. Het is een prachtige kerk uit de 14de eeuw. Deze kerk is wel 123 meter hoog en het middelpunt van de stad Antwerpen. Als je jouw date hiermee naartoe hebt genomen en alles heb laten zien, kan je daarna de stad in duiken om gezellig wat te gaan drinken samen. Ook de zoo van Antwerpen is leuk voor een eerste date. Maar een wandeling langs <a href='http://www.reizen-langs-rivieren.nl/de-schelde-van-bron-tot.html' target='_blank'>de Schelde</a> kan een date helemaal romantisch maken. Dating Antwerpen heeft genoeg mogelijkheden dus nu moet jij alleen nog een date scoren. Kijk snel tussen de contactadvertenties Antwerpen en vind jouw match op de beste gratis datingsite van België!</p>",
						'img' 	=>	"antwerpen"
						),
					"brussel" => array(

						'name' 	=> 	"Brussels",
						'title' 	=> 	"Dating Brussel",
						'info' 	=>	"In Brussel lopen zulke knappe dames rond, alleen zijn er nog heel veel single en op zoek naar een leuke date in Brussel. Heb jij jouw knappe dame tussen de contactadvertenties Brussel al gevonden? Een dagje daten in Brussel is meer dan genoeg om jouw date een succes te maken. Vraag haar op date en laat haar genieten zoals een echte heer dat doet! Dating Brussel heeft zoveel te bieden. Heb je haar al een berichtje gestuurd? Wacht niet langer en kijk tussen de Dating van Brussel!",
						'tekst' 	=> 	"<h3>Wat te doen op een date in Brussel?</h3><p>Brussel is een hele grote stad en daar zijn nog zeker 10.000 singles die avonden alleen zijn. Zij hebben nooit een leuke date in Brussel gehad om eens een mooie <a href='https://visit.brussels/nl/article/originele-rondleidingen-door-brussel' target='_blank'>rondleiding door de stad</a> te krijgen. Daten in Brussel is perfect voor een date met jouw droomvrouw. Neem haar eens mee naar de <a href='https://cathedralisbruxellensis.be/nl/' target='_blank'>Kathedraal van Sint-Michel en Sint-Goedele</a> bijvoorbeeld. Er is namelijk maar liefst 300 jaar gewerkt aan deze gotische kerk aan het Sinter-Goedelevoorplein. Helaas is er tijdens de Franse Revolutie veel van de inhoudelijke rijkdom verloren geraakt. Maar niets maakt het minder waard om het een bezoekje te brengen. Het is prachtig om eens langs te wandelen en de historie te ontdekken die er nog aanwezig is. Maar dating Brussel heeft nog veel meer prachtige plekken voor een date.</p><h4>Waar kan je het beste daten in Brussel</h4><p>In <a href='https://www.groeneruimten.brussels/?_ga=2.172447083.931655013.1553859952-1129464503.1553859952' target='_blank'>het Jubelpark</a> van de koning Leopold ll die destijds is aangelegd is zeer zeker een bezoekje waard als het gaat om een romantische maar ook een gezellige date in Brussel. Hier kan je heerlijk wandelen en nog een stukje geschiedenis terug vinden. Ook kan je daar lekker zitten op het gras met een kleedje en jouw date laten genieten van de omgeving. Waar het tijdens het daten in Brussel ook leuk kan zijn is op de <a href='https://www.brussel.be/grote-markt-van-brussel' target='_blank'>Grote Markt</a>. Tussen de bedrijvigheid van het toerisme samen met je date een drankje doen of een hapje eten in de vele restaurants is zeker een aanrader. Dating Brussel is ook in de avond erg succesvol. Er zijn genoeg barretjes waar jullie samen gezellig kunnen praten onder het genot van een drankje. Dating België is de beste datingsite om te daten in Brussel. Laat jouw kans dus niet voorbij gaan!</p><h4>Dating Brussel</h4><p>Wil je toch liever wat anders doen? Dan is een bezoekje aan de antiekmarkt van de Grote Zavel het zeker waard. Daar vind je veel trendy en hippe winkels maar ook gezellige terrassen. Met jouw date heerlijk door de straten te struinen, arm in arm natuurlijk, om er een gezellige dag van te maken. Je kan daar van alles eten en drinken het is echt een nationale trekpleister voor veel toeristen. Maar ook mensen uit Brussel zelf, zijn er dagelijks te vinden. Een bezoek aan de antiekmarkt is zeker een must en je kan hier de hele dag door heerlijk vertoeven. Dating Brussel heeft zoveel te bieden waar de vorige activiteiten een goed voorbeeld van zijn. Wacht dus niet langer en zet de stap op de beste datingsite voor jouw date in Brussel. Kijk tussen de contactadvertenties Brussel of jouw droomvrouw ertussen zit.</p>",
						'img' 	=>	"brussel"
						),
					"henegouwen" => array(

						'name' 	=> 	"Henegouwen",
						'title' 	=> 	"Dating Henegouwen",
						'info' 	=>	"Dating Henegouwen heeft de mooiste vrouwen van België. Dit is de provincie waar de meeste dames sexy en schaars gekleed rond lopen. Al deze vrouwen zijn nog single en zoeken een date in Henegouwen. Wil jij je arm om haar heen slaan en haar man zijn? Zoek haar tussen de contactadvertenties Henegouwen en stuur haar een gratis berichtje, voordat een ander ermee vandoor gaat. Jij laat je date toch ook niet lopen? Daten in Henegouwen was nog nooit zo makkelijk.",
						'tekst' 	=> 	"<h3>Wat te doen op een date in Henegouwen?</h3><p>Dating Henegouwen is immens populair en heeft heel veel opties voor een leuke date. In Henegouwen vind je nog zeker meer dan 10.000 single vrouwen die wachten op hun droomman. Zij hopen gevraagd te worden om samen van Henegouwen te genieten. Niet alleen in de steden is het mooi om een romantische date te mogen hebben. Ook een wandeling door een nationaal park kan een date in Henegouwen kleur geven. Henegouwen heeft een mooie historie met plaatsen waar jullie er veel van terug kunnen zien. Jouw date kan kiezen uit veel activiteiten die zij graag wilt. Weet jij al wat zij zou kiezen? Lees verder om te zien uit welke opties zij kan kiezen voor een date in Henegouwen.</p><h4>Waar kan je het beste daten in Henegouwen</h4><p>Zij kan bijvoorbeeld kiezen voor de machtige <a href='https://www.villers.be/nl' target='_blank'>Cistercienzerabdij van Villers-la-Ville</a> uit de 12e eeuw. Dit is namelijk een van de oudste stukken Europese stad die overgebleven is. Het is nog heel mooi intact is gebleven en zeker het bezoeken waard. Zo ziet men daar nog steeds de grote abdijkerk met haar twee geveltorens. Dit is een prachtig gebied om jouw date eens een rondleiding te geven en haar terug te brengen in de tijd van de 12e eeuw. Je vind daar nog steeds de grote eetzaal, de verwarmde ruimte en de keuken zoals die er vroeger uit zagen. Dan heb je verder ook nog de lekenvleugel in het westen en vele andere mooie dingen om te zien. De monikkenvleugel en de bibliotheek zijn er nog te bezichtigen en een bezoekje waard om jouw date het genot te geven van een prinses te mogen zijn voor 1 dag.</p><h4>Dating Henegouwen</h4><p>Wil je nog even een drankje nuttigen, dan kan je in de omgeving genoeg restaurantjes vinden. Daar kan je bij komen van een stevige wandeling en de indrukken die je onderweg hebt opgedaan. Wil je jouw date romantischer maken en het een beetje rustiger houden? Dan kan je haar meenemen naar <a href='https://www.natuurenbos.be/kluisbos' target='_blank'>het kluisbos</a>. Dat is een prachtig bos waar je een wandeling kan maken op 300 hectare van de Vlaamse Ardennen. Als je eenmaal een uurtje hebt gewandeld, wil je natuurlijk even rustig kunnen zitten. Een picknick is dan ideaal om samen met jouw date door te brengen. Op een kleedje verhalen aan elkaar vertellen of het hemd van het lijf vragen, zodat je meer te weten komt over jouw date. Dating Henegouwen heeft genoeg opties dus wacht niet langer en zoek een date in Henegouwen. Kijk deze gratis dating site tussen de Dating Henegouwen of jouw droomdate ertussen zit.</p>",
						'img' 	=>	"henegouwen"
						),
					"limburg" => array(

						'name' 	=> 	"Limburg",
						'title' 	=> 	"Dating Limburg",
						'info' 	=>	"Limburg een prachtige provincie met prachtige vrouwen die nog steeds op zoek zijn naar een leuke date in Limburg. Deze single zijn het wachten beu en willen gelijk afspreken. Heb jij jouw date al gevonden waar jij mee wil daten in Limburg? Stuur haar gerust een gratis berichtje en gegarandeerd dat dit een spannende date gaat worden. Dating Limburg is erg populair dus er is keuze genoeg. Zoek tussen de contactadvertenties Limburg nu jouw toekomstige partner!",
						'tekst' 	=> 	"<h3>Wat te doen op een date in Limburg?</h3><p>Woon je in Limburg en ben je nog vrijgezel? Niet getreurd want daten in Limburg heeft genoeg te bieden. Hier lees jij hoe jij een leuke date in Limburg kan hebben samen met jouw nieuwe date. Wil jij op je date actieve en gezellige dingen beleven? Dan is Limburg de plaats om gezien te worden met de mooiste vrouw van Limburg aan je zijde. Dating Limburg is er populair en er zijn meer dan 10.000 vrouwen single. Deze singles zoeken nog geen leuke man aan de haak te slaan. Daarom is Limburg de perfecte provincie om je date mee naartoe te nemen.</p><h4>Waar kan je het beste daten in Limburg</h4><p>Wil je indruk maken op jouw date dan is Valkenburg een plek om zeker eens te bezoeken. Hier heb je bijvoorbeeld de <a href='https://www.kasteelvalkenburg.nl/' target='_blank'>Fluweelengrot</a> die nauw verbonden is met de rijke historie van de kasteelruïne. Het gangenstelsel onder de kasteelruïne van de Fluweelengrot is vermoedelijk in de 11e of 12e eeuw ontstaan. Je kunt er tal van geheime gangen in wandelen die in 1973 ontdekt zijn. Wil je jouw date een spannend avontuur laten beleven? Dan is de Fluweelengrot zeker een bezoekje waard. Je kan na afloop in de omliggende restaurantjes wat eten en of drinken. Heel gezellig even zitten om met je date tot spannende verhalen te komen over de grotten.</p><h4>Dating Limburg</h4><p>Waar vrouwen van houden is natuurlijk mooie bloemen. Wat dan ook echt aan te raden is om met jouw date op bezoek te gaan bij de prachtige tuinen van <a href='https://kasteeltuinen.nl/nl/' target='_blank'>kasteeltuin Arcen</a>. Je kunt daar een heerlijke wandeling maken door de tuinen omringd met prachtige bloemen en planten. Het park heeft zo’n 32 hectare unieke tuinen en een mooie buitenplaats om eens op je gemak doorheen te wandelen. Je kan een tasje meenemen om wat lekkere snacks in te bewaren en in de tuinen samen met je date lekker te gaan zitten om wat te nuttigen. Al met al zijn de kasteeltuinen van Arcen zeker aan te raden voor een perfecte eerste date. De vrouw van je dromen kan je laten zien wat voor soorten bloemen er allemaal te bezichtigen zijn. De romantiek zal ervan af stralen.</p>",
						'img' 	=>	"limburg"
						),
					"luik" => array(

						'name' 	=> 	"Luik",
						'title' 	=> 	"Dating Luik",
						'info' 	=>	"Ben jij het alleen zijn ook zo beu? Dating Luik heeft de gezelligste vrouwen van de provincie voor jou verzamelt. Deze dames willen ook niet alleen zijn en zoeken een date in Luik. Zoek tussen de contactadvertenties Luik naar jouw droomdate. Vraag jij je toekomstige partner mee om gezellig te daten in Luik? Welke man laat zijn vrouw nou wachten, kom op en stuur haar een gratis berichtje. Er zijn genoeg Dating om jouw droomvrouw te kunnen vinden.",
						'tekst' 	=> 	"<h3>Wat te doen op een date in Luik?</h3><p>Voor de perfecte date, moet je in Luik zijn. Hier zijn zeker 10.000 singles die nog nooit een date in Luik hebben gehad. Sterker nog soms zijn ze zelfs niet in Luik op stap zijn geweest. Wil je jouw date perfect laten verlopen, dan is Luik zeker een aanwezen plaats om eens te bezoeken. Zo kan je gaan voor een actieve date bijvoorbeeld <a href='http://walloniebelgietoerisme.be/nl/content/buerenberg' target='_blank'>de trappen van Bueren</a> bewandelen. Let wel op dit vergt wat conditie, want er zijn zo’n 374 traptreden om naar de top te  wandelen. Eenmaal bovenaan de top wordt je getrakteerd op een prachtig uitzicht over de stad Luik en de Maas. Zo kun je echt een prachtige rustgevende wandeling maken door het groenste deel van Luik. Tussen de terrassen door vind je een plekje om met jou ultieme date lekker te gaan zitten om even een drankje tot je te nemen.</p><h4>Waar kan je het beste daten in Luik</h4><p>Om de perfecte date in Luik te hebben, kan je na deze wandeling en als je op adem bent gekomen nog even langs de oude kloosters wandelen. Dit is daar niet alleen een hele populaire trekpleister maar ook zeker de moeite waard te bezoeken. Hier ben je ervan verzekerd dat jouw date graag nog eens deze stad wilt bezoeken. Want er is genoeg om te bezichtigen en even lekker wat te eten of drinken. Luik is daarom gekozen tot de top 10 steden om te bezoeken en een van de beste dating plekken om met jouw spannende date eens eropuit te gaan.</p><h4>Dating Luik</h4><p>Wist je dat het Paleis van de <a href='http://walloniebelgietoerisme.be/nl/produit/attractions/activites/bouwkundig-erfgoed/paleis-van-de-prins-bisschoppen-in-luik/15165' target='_blank'>Prins-Bisschoppen</a> ook in Luik te vinden is? Dit is een prachtig paleis en een van de mooiste gebouwen van de stad. Als je jouw date daarmee naartoe neemt, dan zullen haar ogen glinsteren. Het is allemaal prachtig om te zien en ook zeker een bezoekje waard als je dan toch lekker met je date arm in arm door de stad wandelt. Dating Luik heeft zoals hierboven te lezen is veel te bieden. Wacht dus niet langer en begin met daten in Luik.</p>",
						'img' 	=>	"luik"
						),
					"luxemburg" => array(

						'name' 	=> 	"Luxemburg",
						'title' 	=> 	"Dating Luxemburg",
						'info' 	=>	"Dating Luxemburg heeft keuze genoeg aan vrouwen, want er zijn zoveel vrouwen die willen daten in Luxemburg. Heb jij tussen de contactadvertenties Luxemburg al gezien welke vrouw dit is? Als jij haar een gratis berichtje stuurt, kan jij dit zelf aan haar vertellen. Dan heb jij vandaag nog die spannende date in Luxemburg. Wacht niet te lang zodat jouw kans voorbij gaat. Dating België is een gratis datingsite dus jij hebt niets te verliezen.",
						'tekst' 	=> 	"<h3>Wat te doen op een date in Luxemburg?</h3><p>Ook Luxemburg is een stad die zeker in de top 10 is beland en niet alleen omdat daar de knapste singles. De knapste singles zijn nog op zoek naar hun droompartner. Luxemburg is ook een provincie die zeker in het rijtje thuis hoort om met jouw date te ontdekken. Zo zijn er prachtige natuurparken om eens doorheen te wandelen. Het <a href='https://www.visitluxembourg.com/nl/regios/natuurpark-boven-sure' target='_blank'>natuurpark Boven Sure</a> bijvoorbeeld is heerlijk om eens doorheen te lopen met de date van jouw dromen. Bezoek met jouw date de prachtige kastelen <a href='http://www.vianden-info.lu/nederlands/bezoeken-und-ontdekkingen/historisch-erfgoed/het-kasteel-van-vianden' target='_blank'>Vianden</a> en <a href='https://beaufortcastles.com/nl/' target='_blank'>Beaufort</a> of breng een bezoekje aan het karakteristieke Larochette. Daarnaast is er ook het Nationaal Museum van de geschiedenis en kunst. Er is dus genoeg te doen op een date in Luxemburg, dus lees verder hoe jij daten in Luxemburg tot een succes kan maken.</p><h4>Waar kan je het beste daten in Luxemburg</h4><p>Wil je met jouw date een actieve date laten plaatsvinden? Luxemburg heeft bijvoorbeeld ook de Ardennen die niet te ver zijn om eens heen te rijden. Je vind daar de rotsachtige heuvels en zo kan je genieten van de mooie uitzichten. Maar ook kan je er wandelen in een ruim gebied van bossen, zeker 3000 hectare wat tot beschikking is gesteld als wandelgebied. Het zeker een populair gebied voor bergbeklimmers, dus durf je met jouw date de spanning aan de rotsen te beklimmen? Dan is <a href='http://berdorf.be/' target='_blank'>Berdorf</a> de ultieme date om te wandelen en je klimspullen mee te nemen. Daten in Luxemburg heeft nog meer opties zoals de geschiedenis in duiken samen. In Dating Luxemburg lees jij welke activiteiten hiervoor in aanmerking komen. Kijk ondertussen of er op deze gratis datingsite al een vrouw staat die jij wil aanspreken.</p><h4>Dating Luxemburg</h4><p>Een stukje terug de geschiedenis in met jouw date? Dan is het <a href='https://www.mnha.lu/en/Highlight' target='_blank'>Nationaal Museum van de geschiedenis en kunst</a> leuk om eens te bezichtigen, je vind daar namelijk veel kunstvoorwerpen en archeologische vondsten, gereedschap, meubelen, wapens en documenten over de geschiedenis. Al met al vind jouw perfecte dat plaats in het museum en kan je naar afloop samen in de omliggende omgeving heerlijk eten of drinken. Het Vianden kasteel is zeer zeker aan te raden om met jouw date eens te bezoeken. Het ligt namelijk op een rotsachtige berg en heeft een prachtig uitzicht als je bovenaan de top bent komen wandelen. Dit kasteel hoort zeker in de top 10 thuis om jouw date eens mee naartoe te nemen. Dating Luxemburg heeft genoeg opties voor een leuke date. Wacht niet langer en ga daten in Luxemburg. Kijk tussen de Dating Luxemburg of jouw droomvrouw ertussen staat.</p>",
						'img' 	=>	"luxemburg"
						),
					"namen" => array(

						'name' 	=> 	"Namen",
						'title' 	=> 	"Dating Namen",
						'info' 	=>	"In Namen zijn heel veel single dames alleen en eenzaam. Deze dames hebben nog steeds niet de juiste partner gevonden, zij wachten tot zij meegevraagd worden op een spannende date in Namen. Dating Namen heeft veel dames die een toekomst willen opbouwen met de juiste man. Maar pas op! Er zijn singles die alleen voor een spannende date gaan. Heb jij haar al gevonden tussen de contactadvertenties Namen? Wacht niet langer en stuur jou date een gratis bericht om snel te gaan daten in Namen.",
						'tekst' 	=> 	"<h3>Wat te doen op een date in Namen?</h3><p>Namen is niet alleen de plaats waar nog steeds veel te veel vrouwen single wonen, maar ook veel vrouwen die heel graag eens Namen willen bezichtigen. Veel vrouwen zijn nog nooit op een date in Namen geweest. Veel van deze dames staan hier tussen de Dating Namen. Daarom staat Namen in de top 10 om jouw perfecte date te laten verlopen. Het is een mooie rustige omgeving om jouw date te ontmoeten. Wie weet ontdek jij wel dat daten in Namen wel de beste plek is. Dating Namen heeft enorm veel te bieden. Lees hier welke plekken het bezoeken waard zijn met jouw date.</p><h4>Waar kan je het beste daten in Namen</h4><p>In het <a href='https://www.namurtourisme.be/nl/' target='_blank'>centrum van Namen</a>, met zijn smalle straatjes en mooie pleinen, is daten perfect. Een relaxte dag om al deze winkels af te struinen met jouw date is daar zeker een optie. Als je verzekerd bent van jouw date dat dit nog weleens een relatie zou kunnen worden, waarom dan niet eens ergens overnachten? Is dat een goed plan dan is een luxe overnachting in het hotel <a href='http://www.chateaudenamur.com/NL/hotel' target='_blank'>Le Chateau</a> ook zeker een bezoekje waard. Hier kunnen jullie romantisch te overnachten en de date met succes afsluiten. Wil je gewoon een gezellige dagje uit en je niet druk hoeven maken dat jouw date het naar haar zin heeft? Dan is de rommelmarkt van Namen heerlijk om eens doorheen te struinen. Deze is iedere zondag vanaf 8 uur tot en met 13 uur bij de rivier te vinden. Ergens even een pauze nemen en wat eten maakt jouw date in Namen helemaal af.</p><h4>Dating Namen</h4><p>Wil je met jouw date in de romantische sferen blijven? Dan is bij de rots van het fort nog <a href='https://www.citadellededinant.be/nl/' target='_blank'>een prachtig kasteel</a> te vinden die meer dan 2000 jaar oud is. Daar heb je zeker 5 wandelroutes waar u alleen met uw date kunt wandelen of kan laten leiden door een gids. Die gids kan jullie alles vertellen over de historie van het kasteel. Er lopen onder het kasteel door velen gangen en wandelroutes waar ook nog de overblijfselen van verschillende periodes te bezichtigen zijn. Heel mooi om even te mogen ontdekken en je te laten wanen door de geschiedenis van Namen.  Jouw date in Namen afsluiten met een <a href='http://walloniebelgietoerisme.be/nl/produit/attractions/activites/riviertochten/toeristische-boottochten-op-de-maas/14577' target='_blank'>rondvaart over de rivier</a> is zeker een must. Dating Namen heeft nog veel meer mogelijkheden maar met deze voorbeelden moet jouw eerste date wel een succes worden. Wacht niet langer en kijk snel tussen de Dating Namen.</p>",
						'img' 	=>	"namen"
						),
					"oost-vlaanderen" => array(

						'name' 	=> 	"Oost-Vlaanderen",
						'title' 	=> 	"Dating Oost-Vlaanderen",
						'info' 	=>	"De spannendste dames komen uit Oost-Vlaanderen. Zij wachten al zo lang tot hun prins ze komt bevrijden. De meeste zijn al een tijdje single en branden van verlangen naar spannende date in Oost-Vlaanderen. Neem jij haar mee om te daten in Oost-Vlaanderen? Dating Oost-Vlaanderen heeft veel keus dus zoek snel tussen de Dating. Klik snel op de vrouw naar keuze en stuur haar een gratis chatbericht!",
						'tekst' 	=> 	"<h3>Wat te doen op een date in Oost-Vlaanderen?</h3><p>In Oost-Vlaanderen slaat je hart op hol, er zijn zoveel singles die wachten op hun droom partner en nog steeds niet gevonden zijn. In Oost-Vlaanderen kan je jouw date meenemen naar tal van leuke dorpjes. Of misschien wel de Gravensteen van Gent. Nergens anders ter wereld staat namelijk de massieve Burcht als deze midden in het stadscentrum. Wie Gent bezoekt met zijn of haar date, weet zeker dat dit een dag vol bewondering zal zijn. Want diegene die het <a href='https://gravensteen.stad.gent/' target='_blank'>Gravensteen</a> bezoekt met zijn date en zich gaat verdiepen in de geschiedenis van de stad, zal hier zeker nog over napraten op een volgende date.</p><h4>Waar kan je het beste daten in Oost-Vlaanderen</h4><p>Wil je graag jouw date meenemen en een stukje kunst uit Oost-Vlaanderen laten zien? Dan kan je jouw date meenemen naar de Ronde van Vlaanderen. Daar beleef je de unieke sfeer van de Ronde van Vlaanderen in het <a href='https://crvv.be/' target='_blank'>CRVV</a> en ervaar samen met jouw date wat voor mooie kunstwerken er zijn uit de geschiedenis. Als je dan toch een rondje hebt gedaan met jouw droomdate, loop dan even binnen bij de brasserie voor een lekker hapje en of drankje om het goed af te sluiten. Alsof dat nog niet genoeg is, kan je jouw droomvrouw natuurlijk ook eens meenemen naar de leuke kroegjes. Oost-Vlaanderen biedt genoeg leuke cafes zoals <a href='https://www.dorst.be/welkom' target='_blank'>In de Verzekering tegen de Grote dorst</a>. Dit is het enige cafe aan het dorpsplein Eizeringen, maar een heerlijke plek om even te zitten. Samen met jouw date een drankje te nuttigen, zeg nou zelf dat zou toch geweldig zijn!</p><h4>Dating Oost-Vlaanderen</h4><p>Iedereen lust toch wel een lekker wijntje of biertje? Ook dat is hier te krijgen en je zal een gezellige avond hebben met jouw date. Als afsluiter van jouw date, kunnen wij je zeker aanraden om nog eens door het <a href='https://www.kasteelvangaasbeek.be/nl/park-en-museumtuin' target='_blank'>museumtuin van Gaasbeek</a> te wandelen, als je er goed rond kijkt, vind je vast nog wel wat peren bomen die er staan en al eeuwenoud zijn. Er zijn dus genoeg leuke activiteiten voor een date in Oost-Vlaanderen. Kijk snel tussen de Dating Oost-Vlaanderen om jouw droomvrouw uit te nodigen voor een leuke date.</p>",
						'img' 	=>	"oost-vlaanderen"
						),
					"vlaams-brabant" => array(

						'name' 	=> 	"Vlaams-Brabant",
						'title' 	=> 	"Dating Vlaams-Brabant",
						'info' 	=>	"Waar komen de mooiste vrouwen vandaan? Juist! Vlaams-Brabant. Deze dames laat jij toch niet wachten op een mooie date in Vlaams-Brabant? Al deze vrouwen zijn single en willen dat hun hartje veroverd wordt door de juiste partner. Heb jij haar al tussen de contactadvertenties Vlaams-Brabant gezien? Stuur haar dan snel een gratis berichtje en neem haar mee om te gaan daten in Vlaams-Brabant!",
						'tekst' 	=> 	"<h3>Wat te doen op een date in Vlaams-Brabant?</h3><p>Vlaams-Brabant zegt het eigenlijk al, er zijn zoveel singles die nog geen levenspartner hebben gevonden. Zij wachten tot jij haar meeneemt naar een stukje geschiedenis uit Vlaams-Brabant. Weet je niet wat je op zo’n eerste date moet doen? Neem je date mee naar het <a href='http://www.visitbeersel.be/product/1044/kasteel-van-beersel' target='_blank'>kasteel van Beersel</a>. Het kasteel van Beersel is een van de weinige goed bewaarde voorbeelden van de middeleeuwse krijgsbouwkunde in ons land. Het staat er nog steeds zoals het er uitzag aan de einde van de 15e eeuw. Wil je samen met jou date het kasteel bezoeken? Reken er dan op dat je hier een hele dag rond kan lopen en van alles kunt bezichtigen. Een rugzakje met een lekker snack om af en toe eens een pauze in te lassen en rustig te gaan zitten moet je zeker meenemen.</p><h4>Waar kan je het beste daten in Vlaams-Brabant</h4><p>Als we het dan toch over kastelen hebben, kan je jouw gezellige date meenemen naar <a href='https://visit.brussels/nl/place/Jubelpark' target='_blank'>het Jubelpark</a>. Het Jubelpark kan je namelijk heerlijk wandelen en zeker met het mooie weer een hele dag vertoeven. Het Jubelpark is namelijk aangelegd in opdracht van koning Leopold ll om in 1880 de vijftigste verjaardag van de Belgische onafhankelijkheid te vieren. Er staan hele mooie kartelachtige monumentale pandjes die zeker een bezichtiging waard zijn met jouw droomvrouw.</p><h4>Dating Vlaams-Brabant</h4><p>Er zijn ontzettend veel oude kastelen en kerken te bekijken in Vlaams-Brabant. Je weet zeker als je jouw vrouw meeneemt op date, dat je hier misschien wel meerdere dagen voor uit kan trekken, redt je het niet met jouw date om binnen een dag door Vlaams-Brabant te wandelen, dan kan je een hotel nemen voor een paar overnachtingen om de volgende dag nog eens de <a href='http://www.basilicakoekelberg.be/documents/home.xml' target='_blank'>Basiliek van Koekelberg</a> te bezoeken, of misschien wel de <a href='https://www.toerismevlaamsbrabant.be/producten/bezoeken/bezienswaardigheden/sintkwintenskerk/' target='_blank'>Sint-Kwintenskerk</a>? De kerk is wel gerestaureerd maar ook zeker nog hele mooie oude historie te ontdekken. Al met al zijn er dus genoeg mooie plekken te bezoeken op een date in Vlaams-Brabant. Wacht dus niet langer en kijk tussen de Dating Vlaams-Brabant.</p>",
						'img' 	=>	"vlaams-brabant"
						),
					"waals-brabant" => array(

						'name' 	=> 	"Waals-Brabant",
						'title' 	=> 	"Dating Waals-Brabant",
						'info' 	=>	"Dating Waals-Brabant een gouden provincie met veel single vrouwen die goud waard zijn. Heb jij jouw keuze tussen de contactadvertenties Waals-Brabant al gemaakt? Laat je single dame niet langer wachten en stuur haar snel een gratis berichtje. Je bent verzekerd van een lieve vrouw die jij kan meenemen op een leuke date in Waals-Brabant. Daten in Waals-Brabant was nog nooit zo makkelijk als op Dating België, niet voor niets de beste datingsite van België.",
						'tekst' 	=> 	"<h3>Wat te doen op een date in Waals-Brabant?</h3><p>Heb je al gehoord dat er in Waals-Brabant meer single vrouwen rondlopen dan mannen? Nee? Dit maakt daten in Waals-Brabant alleen maar makkelijker. Maar waar moet jij op een date in Waals-Brabant gaan doen? Wij hebben een paar tips op een rijtje gezet om jouw single vrouw eens op date te vragen. Zo kan jij haar Waals-Brabant laten zien. In Waals-Brabant heb je bijvoorbeeld de <a href=https://www.toerismevlaamsbrabant.be/producten/bezoeken/bezienswaardigheden/sintgorgoniuskerk-hoegaarden/ target=_blank>Sint-Gorgoniuskerk</a> een prachtig plaatje om te zien. De toren die domineert en uitsteekt boven de stad. De kerk staat bekend om de grootste rococokerk van het land. Trouwens in 1754-59 nadat de oudere romaanse kerk was ingestort is deze kerk pas gebouwd. Als je graag een date wil die zekerheid kan bieden op een goede afloop, dan is deze kerk zeker een bezoekje waard.</p><h4>Waar kan je het beste daten in Waals-Brabant</h4><p>Wil je jouw date romantischer maken en het vrouwtje van je dromen helemaal voor jezelf hebben? Dan is het <a href=https://www.hallerbos.be/ target=_blank>Hallerbos</a> heerlijk om doorheen te wandelen op een zwoele zomeravond. Er staan prachtige beuken ondanks dat het allemaal nog niet zo oud is vanwege de nieuwe beplanting. Maar ook hier ben je verzekerd van een romantische date. In het bos kan je nog regelmatig oude stukken tegenkomt van de eerste wereldoorlog. Wil je het leuk afsluiten met je date? Dan kan je in de omliggende omgeving in de kleine restaurantjes heerlijk eten met een hele uitgebreide kaart.</p><h4>Dating Waals-Brabant</h4><p>Heb je belangstelling om eens te gaan kijken hoe alles hier is ontstaan uit de ontwikkeling in druiventeelt? Dan neem je jouw date mee naar het <a href=http://www.tento.be/musea/druivenmuseum target=_blank>Druivenmuseum</a>. Het Druivenmuseum is op een zolderverdieping ingericht tot een ware paleis van geschiedenis waar je enkele historische aspecten kan bekijken. Hierbij wordt een uitstekend beeld geschetst van hoe alles tot stand is gekomen. Je mag er niet drinken, maar een flesje wijn meenemen in de tas is wel een goed idee. Die fles kan je ergens op een bankje na afloop met jouw date gaan drinken. Dit verzekerd je van een gezellig date in Waals-Brabant. Zoals je hebt kunnen lezen heeft dating Waals-Brabant genoeg te bieden. Nu is het aan jou om de eerste stap te zetten en te gaan kijken tussen de Dating Waals-Brabant.</p>",
						'img' 	=>	"waals-brabant"
						),
					"west-vlaanderen" => array(

						'name' 	=> 	"West-Vlaanderen",
						'title' 	=> 	"Dating West-Vlaanderen",
						'info' 	=>	"De mooiste vrouwen uit de provincie wachten op een spannende date in West-Vlaanderen. Al deze vrouwen zijn momenteel online en wachten op die overheerlijk zoen van hun droomman. Jij laat je dame toch niet wachten om te gaan daten in West-Vlaanderen? Maak snel gratis contact en wie weet heb jij vanavond nog geluk. Dating West-Vlaanderen heeft keuze genoeg dus kijk snel tussen de Dating of jouw droomvrouw ertussen staat.",
						'tekst' 	=> 	"<h3>Wat te doen op een date in West-Vlaanderen?</h3><p>Met ruim 10.000 singles in West-Vlaanderen zijn er genoeg mannen en vrouwen die op zoek zijn naar een partner. Toch blijk het niet eenvoudig om een partner te vinden die naar alle wensen en behoefte voldoet als u. Maar als u haar eenmaal gevonden hebt, wilt u haar toch ook meenemen op een gezellige date? Zo kan je in West-Vlaanderen je date meenemen naar de kunsteden of misschien wel de natuur? In West-Vlaanderen kan je heerlijk wandelen in de natuur <a href='https://www.west-vlaanderen.be/domeinen/palingbeek' target='_blank'>De Palingbeek</a> bijvoorbeeld. Jouw date mee nemen om te picknicken, gezellig zitten op een kleedje, is heel erg romantisch. Dating West-Vlaanderen heeft voor elke single een leuke gelegenheid om eens naartoe te gaan.</p><h4>Waar kan je het beste daten in West-Vlaanderen</h4><p>Wil je een romantische date die toch wat actiever is dan gezellig zitten op een kleedje? Dan is een stukje historie laten zien aan de vrouw van je dromen misschien wel de oplossing. Het <a href='http://www.kasteelvanrumbeke.be/_pages/nl/bezoeken.htm' target='_blank'>kasteel van Rumbeke</a> is ook zeker een aanrader. Het kasteel van Rumbeke is het meesterwerk van de Vlaamse Renaissance en dateert uit 1538 en is een van de oudste kastelen van België. Wil je jouw princes daar rond begeleiden dan is dit zeker een bezoek waardig. Na afloop gezellig met jouw date een heerlijk hapje eten kan in de buurt. Ook kan je gewoon ergens een terrasje pakken en lekker zitten om wat te drinken. Je bent ervan verzekerd dat jouw date een tweede kans krijgt en je bij de volgende date met jouw droomvrouw iets anders kan bezoeken. Dating West-Vlaanderen heeft genoeg mogelijkheden te bieden voor meerdere spannende dates met jouw droomvrouw.</p><h4>Dating West-Vlaanderen</h4><p>Wil je het toch liever anders aanpakken? Dan kan je jouw droomdate meenemen naar <a href='https://www.flandersfields.be/nl/doen/menenpoort' target='_blank'>de Menenpoort</a>. De Menenpoort wordt beschouwd als algemeen symbool voor de eerste wereldoorlog. Het is zeker een bezoekje waard als je van historie houdt. Daten in West-Vlaanderen heeft nog tal van leuke activiteiten, te veel om hier allemaal te noemen zelfs. Nu jij onze dating tips hebt gelezen is het aan jou om de volgende stap te zetten. Kijk snel tussen de Dating West-Vlaanderen of jouw droomvrouw ertussen zit. Stuur haar een gratis bericht en nodig haar uit om te gaan daten in West-Vlaanderen.</p>",
						'img' 	=>	"west-vlaanderen"
						)
					);
?>